/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MetaFields {
  title: string
  description: string
  imageUrl: string
  faviconUrl: string
}
export function fetchMetaFields(url: string): MetaFields
